var age = 25;
console.log(age);
age = true;
console.log(age);
var mixed = [];
mixed.push(5);
mixed.push('hello');
mixed.push(true);
console.log(mixed);
var obj;
obj = { mane: 23, age: 'Jack' };
console.log(obj);
